services:

  db-host-backup:
    container_name: db-host-backup
    image: postgres:17-alpine
    env_file:
      - env/db.env
    ports:
      - "5457:5432"
    volumes:
      - ./backups/full-1/:/var/lib/postgresql/data/

#    healthcheck:
#      test: [ "CMD", "pg_isready", "-q", "-d", "users_db", "-U", "users_db_app_user" ]
#      interval: 5s
#      timeout: 60s
#      retries: 5
#      start_period: 80s