# Hibernate logging configuration
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace #Show actual values written to the DB
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG